name: Bug report
description: Report a reproducible defect
title: "[Bug]: "
labels:
  - bug
assignees:
  - Faerkeren
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version, commit SHA, or branch are you using?
      placeholder: "v0.1.0 or commit SHA"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal sequence that reproduces the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and traceback
      description: Paste relevant logs, traceback, or screenshots
      render: shell
