name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.

  - type: input
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
      placeholder: I want to ... because ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior or API you would like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: additional
    attributes:
      label: Additional context
