from enum import Enum


class PortSide(str, Enum):
    UNDEFINED = "UNDEFINED"
    NORTH = "NORTH"
    EAST = "EAST"
    SOUTH = "SOUTH"
    WEST = "WEST"


class PortConstraint(str, Enum):
    UNDEFINED = "UNDEFINED"
    FREE = "FREE"
    FIXED_SIDE = "FIXED_SIDE"
    FIXED_ORDER = "FIXED_ORDER"
    FIXED_RATIO = "FIXED_RATIO"
    FIXED_POS = "FIXED_POS"


class PortLabelPlacement(str, Enum):
    INSIDE = "INSIDE"
    OUTSIDE = "OUTSIDE"
    NEXT_TO_PORT_IF_POSSIBLE = "NEXT_TO_PORT_IF_POSSIBLE"
    ALWAYS_SAME_SIDE = "ALWAYS_SAME_SIDE"
    ALWAYS_OTHER_SAME_SIDE = "ALWAYS_OTHER_SAME_SIDE"
    SPACE_EFFICIENT = "SPACE_EFFICIENT"


class NodeLabelPlacement(str, Enum):
    INSIDE = "INSIDE"
    OUTSIDE = "OUTSIDE"
    H_LEFT = "H_LEFT"
    H_CENTER = "H_CENTER"
    H_RIGHT = "H_RIGHT"
    V_TOP = "V_TOP"
    V_CENTER = "V_CENTER"
    V_BOTTOM = "V_BOTTOM"
    H_PRIORITY = "H_PRIORITY"


class NodeSizeConstraint(str, Enum):
    PORTS = "PORTS"
    PORT_LABELS = "PORT_LABELS"
    NODE_LABELS = "NODE_LABELS"
    MINIMUM_SIZE = "MINIMUM_SIZE"


class NodeSizeOption(str, Enum):
    DEFAULT_MINIMUM_SIZE = "DEFAULT_MINIMUM_SIZE"
    MINIMUM_SIZE_ACCOUNTS_FOR_PADDING = "MINIMUM_SIZE_ACCOUNTS_FOR_PADDING"
    COMPUTE_PADDING = "COMPUTE_PADDING"
    OUTSIDE_NODE_LABELS_OVERHANG = "OUTSIDE_NODE_LABELS_OVERHANG"
    PORTS_OVERHANG = "PORTS_OVERHANG"
    UNIFORM_PORT_SPACING = "UNIFORM_PORT_SPACING"
    FORCE_TABULAR_NODE_LABELS = "FORCE_TABULAR_NODE_LABELS"
    ASYMMETRICAL = "ASYMMETRICAL"


class EdgeType(str, Enum):
    NONE = "NONE"
    DIRECTED = "DIRECTED"
    UNDIRECTED = "UNDIRECTED"
    ASSOCIATION = "ASSOCIATION"
    GENERALIZATION = "GENERALIZATION"
    DEPENDENCY = "DEPENDENCY"


class EdgeLabelPlacement(str, Enum):
    CENTER = "CENTER"
    HEAD = "HEAD"
    TAIL = "TAIL"


class EdgeRouting(str, Enum):
    UNDEFINED = "UNDEFINED"
    POLYLINE = "POLYLINE"
    ORTHOGONAL = "ORTHOGONAL"
    SPLINES = "SPLINES"


class EdgeRoutingMode(str, Enum):
    NONE = "NONE"
    MIDDLE_TO_MIDDLE = "MIDDLE_TO_MIDDLE"
    AVOID_OVERLAP = "AVOID_OVERLAP"


class Direction(str, Enum):
    UNDEFINED = "UNDEFINED"
    RIGHT = "RIGHT"
    LEFT = "LEFT"
    DOWN = "DOWN"
    UP = "UP"


class LayeringStrategy(str, Enum):
    NETWORK_SIMPLEX = "NETWORK_SIMPLEX"
    LONGEST_PATH = "LONGEST_PATH"
    LONGEST_PATH_SOURCE = "LONGEST_PATH_SOURCE"
    COFFMAN_GRAHAM = "COFFMAN_GRAHAM"
    INTERACTIVE = "INTERACTIVE"
    STRETCH_WIDTH = "STRETCH_WIDTH"
    MIN_WIDTH = "MIN_WIDTH"
    BF_MODEL_ORDER = "BF_MODEL_ORDER"
    DF_MODEL_ORDER = "DF_MODEL_ORDER"
